news/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import  i18n_patterns

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('silk/',include('silk.urls',namespace='silk')),
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    path('', include('posts.urls',namespace='posts'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import *



app_name = 'posts'

urlpatterns = [
    path('base',BaseTemplateView.as_view(),name='base'),
    path('',IndexListView.as_view(),name='index'),
    path('tags/<int:tag_id>/',Tag_view.as_view(),name="tag_view"),
    # path('category/<int:pk>',CategoryView.as_view(),name='category'),
    # path('post/<int:pk>',PostDetailView.as_view(),name='post-detail'),
    path('category/<int:category_id>/posts',CategoryView.as_view(),name="category"),
    path('post/<int:post_id>/',MixinPost.as_view(),name="post-detail"),
    path('audio',AudioListView.as_view(),name='audio'),
    # path('search/',search_results,name="search"),
    path('search',search_post,name='search_post'),
    path('contact',contact,name='contact'),
    path('about',AboutView.as_view(),name='about'),
    path('exem',exemple,name='exem')
]

templates/abaut.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-10">
        <div class="bl-light mb-3" style="padding:30px;">
            <h3>Sayt xaqida</h3>
<h4 class="mb-3">
NEWSROOM jahonda va O'zbekistondan foydalanishga kirishgan yangiliklarni o'zbek o'qishlariga sodda va tushunarli tilda hamda tezkor etib berishga mo'ljallangan internet-nashrdir.

Loyiha 2022 yilning fevralida ishini boshlagan.
    <a href="https://www.facebook.com/ismatillo.ismatov.7"> Facebook</a>,  <a href="https://www.instagram.com/ismatilloismatov/">Instagram</a><a href="https://t.me/Ismatilloismatov"> Telegram</a> va boshqa ijtimoiy tarmoqlardagi sahifalarimiz   ishlamoqda.

NEWSROOM sayti materiallaridan foydalanish shartlari
NEWSROOM sayti taʼmirlanishi mavjud boʻlgan koʻchmachilik boʻyicha saytda chop etilgan materiallar, manbalar asosida koʻchirib chiqilgan maʼlumotlar asosliligi uchun (manbasi saqlab qolingan maʼlumotlarga) javobgarlikni oʻz kuchiga ega boʻlmaydi.
Saytda chop etilgan maqola yuzasidan, chop etish mumkini va sayt tahriyatining fikri boshqa mumkini mumkin.
Shuningdek, sayt ta'minotchilarining yuborgan xatlari, fikrlariga har biriga javob yo'qotish majburiyatini olmaydi.
</h4>
        </div>
    </div>
</div>
<div class="container-fluid py-3">
        <div class="container">
            <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                <h3 style="padding:center" class="m-0">Bizning jamoa</h3>
            </div>

            <div class="owl-carousel owl-carousel-2 carousel-item-4 position-relative">
                {% for t in team %}
                <div class="position-relative overflow-hidden" style="height: 300px;">
                    <img class="img-fluid w-100 h-100" src="{{ t.image.url }}" style="object-fit: cover;">

                    <div class="overlay">
                        <div class="mb-1" style="font-size: 13px;">
                            <a class="text-white" href="">{{ t.name }}</a>
                            <span class="px-1 text-white">/</span>
                            <a class="text-white" href="">{{ t.professional }}</a>
                        </div>
                        <a class="h4 m-0 text-white" href="">{{ post.title }}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
</div>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block  content %}
    <div class="container-fluid py-3">
        <div class="container">
            <div class="bg-light py-2 px-4 mb-3">
                <h3 class="m-0">Contact Us For Any Queries</h3>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="bg-light mb-3" style="padding: 30px;">
                        <h6 class="font-weight-bold">Get in touch</h6>
                        <p>Sayt materiallaridan to'liq yoki qisman foydalanilganda veb-sayt manzilini saqlash shart.​ O'zMAA internet-OAV guvohnomasi raqami: 1124 Rasmiy xabarlarda va bloglarda ketgan ma'lumotlar - maqolalarga mualliflar va blogerlarning o'zlari mas'uldirlar.</p>
                        <div class="d-flex align-items-center mb-3">
                            <i class="fa fa-2x fa-map-marker-alt text-primary mr-3"></i>
                            <div class="d-flex flex-column">
                                <h6 class="font-weight-bold">Our Office</h6>
                                <p class="m-0">Mustaqillik 254, Fergana, Uzbekistan</p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center mb-3">
                            <i class="fa fa-2x fa-envelope-open text-primary mr-3"></i>
                            <div class="d-flex flex-column">
                                <h6 class="font-weight-bold">Email Us</h6>
                                <p class="m-0">ismatilloismatov1995@gmail.com</p>
                            </div>
                        </div>
                        <div class="d-flex align-items-center">
                            <i class="fas fa-2x fa-phone-alt text-primary mr-3"></i>
                            <div class="d-flex flex-column">
                                <h6 class="font-weight-bold">Call Us</h6>
                                <p class="m-0">+998-99-919-51-70</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="contact-form bg-light mb-3" style="padding: 30px;">
                        <div id="success"></div>
                        <form name=  novalidate="novalidate" method="post">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <input type="text"  class="form-control p-4" id="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <input type="email"  class="form-control p-4" id="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                            </div>
<!--                            <div class="control-group">-->
<!--                                <input type="text"  class="form-control p-4" id="subject" placeholder="Subject" required="required" data-validation-required-message="Please enter a subject" />-->
<!--                                <p class="help-block text-danger"></p>-->
<!--                            </div>-->
                            <div class="control-group">
                                <textarea class="form-control"  rows="4" id="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;" type="submit"  id="sendMessageButton">Send Message</button>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>

    </div>
<h2>We in map
</h2>
	<figure class="google_map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1456.0859328437732!2d71.72031365812221!3d40.48267903493471!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bb774f0a105189%3A0x37909c7a10353fbe!2sArtel%20margilan!5e1!3m2!1suz!2s!4v1634317288113!5m2!1suz!2s" width="1200" height="400" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </figure>

    <!-- Contact End -->


{% endblock %}

templates/contactform.html
<h1>Contact form submission</h1>

<p><b>Name:</b>{{ name }}</p>
<p><b>Email:</b>{{ email }}</p>
<p><b>Message:</b>{{ message }}</p>

templates/email_template.html
hey{{name}}

templates/exemple.html
{% extends 'base.html'%}
{% block content %}


<div class="container">
  <blockquote>Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.
    <cite>- Linus Torvalds</cite>
  </blockquote>
</div>
<style>
  
  

</style>
{% endblock %}
<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport"-->
<!--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">-->
<!--    <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">-->
<!--    <title>Autocomplete</title>-->
<!--</head>-->
<!--<body>-->
<!--<form>-->
<!--    <label for="posts">Posts</label>-->
<!--    <input type="text" name="posts" id="posts">-->
<!--</form>-->
<!--<script src="https://code.jquery.com/jquery-1.12.4.js"></script>-->
<!--<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>-->


<!--<!doctype html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport"-->
<!--          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">-->
<!--    <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">-->
<!--    <title>Autocomplete</title>-->
<!--</head>-->
<!--<body>-->

<!--<form>-->
<!--    <label for="posts">Posts</label>-->
<!--    <input type="text" name="posts" id="posts">-->
<!--</form>-->

<!--<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>-->
<!--<script src="https://code.jquery.com/jquery-3.6.0.js"></script>-->
<script>
  $( function() {
    $(" #posts" ).autocomplete({
      source: '{% url "posts:exem" %}',
      minLength:2
    });
  } );
</script>
</body>

templates/left.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
                <div class="col-lg-4 pt-3 pt-lg-0">
                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Follow Us</h3>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #39569E;">
                                <small class="fab fa-facebook-f mr-2"></small><small>12,345 Fans</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #52AAF4;">
                                <small class="fab fa-twitter mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #0185AE;">
                                <small class="fab fa-linkedin-in mr-2"></small><small>12,345 Connects</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #C8359D;">
                                <small class="fab fa-instagram mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #DC472E;">
                                <small class="fab fa-youtube mr-2"></small><small>12,345 Subscribers</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #1AB7EA;">
                                <small class="fab fa-vimeo-v mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->

                    <!-- Newsletter Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Newsletter</h3>
                        </div>
                        <div class="bg-light text-center p-4 mb-3">
                            <p>Aliqu justo et labore at eirmod justo sea erat diam dolor diam vero kasd</p>
                            <div class="input-group" style="width: 100%;">
                                <input type="text" class="form-control form-control-lg" placeholder="Your Email">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                            <small>Sit eirmod nonumy kasd eirmod</small>
                        </div>
                    </div>
                    <!-- Newsletter End -->

                    <!-- Ads Start -->
                    <div class="mb-3 pb-3">
                        <a href=""><img class="img-fluid" src="img/news-500x280-4.jpg" alt=""></a>
                    </div>
                    <!-- Ads End -->

                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tranding</h3>
                        </div>
                                 {% for p in most_view %}

                        <div class="d-flex mb-3">
                            {% if p.image %}
                            <img src="{{ p.image.url  }}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{ p.category }}</a>
                                    <span class="px-1">{{ p.views }}</span>
                                    <span>January 01, 2045</span>
                                </div>
                                <a class="h6 m-0" href="{% url 'posts:post-detail' p.pk %}">{{ p.text|slice:50 }}</a>
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tags</h3>
                        </div>
                        <div class="d-flex flex-wrap m-n1">
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Politics</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Business</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Corporate</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Sports</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Health</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Education</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Science</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Technology</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Foods</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Entertainment</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Travel</a>
                            <a href="" class="btn btn-sm btn-outline-secondary m-1">Lifestyle</a>
                        </div>
                    </div>
                    <!-- Tags End -->
                </div>


</body>
</html>

templates/rightbar.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">{% translate "Follow Us" %}</h3>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="https://www.facebook.com/ismatillo.ismatov.7" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #39569E;">
                                <small class="fab fa-facebook-f mr-2"></small><small>12,345 Fans</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #52AAF4;">
                                <small class="fab fa-twitter mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #0185AE;">
                                <small class="fab fa-linkedin-in mr-2"></small><small>12,345 Connects</small>
                            </a>
                            <a href="https://www.instagram.com/ismatilloismatov/" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #C8359D;">
                                <small class="fab fa-instagram mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="https://www.youtube.com/channel/UCxXljCMJ72Py6UtisNzBY4g" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #DC472E;">
                                <small class="fab fa-youtube mr-2"></small><small>12,345 Subscribers</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #1AB7EA;">
                                <small class="fab fa-vimeo-v mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->



                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tranding</h3>
                        </div>
                                                    {% for p in most_view %}

                        <div class="d-flex mb-3">
                            {% if p.image %}
                            <img src="{{ p.image.url }}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{ p.category }}</a>
                                    <span class="px-1">/</span>
                                    <span>{{ p.post_date }}</span>
                                </div>
                                <a class="h6 m-0" href="{% url 'posts:post-detail' p.pk %}">{{ p.title }}</a>
                            </div>
                            {% endif %}
                        </div>
                                                    {% endfor %}

                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tags</h3>
                        </div>
                        <div class="d-flex flex-wrap m-n1">
                                                    {% for tag in tags %}
                            <a href="{% url 'posts:tag_view' tag.pk %}" class="btn btn-sm btn-outline-secondary m-1">{{ tag.title }}</a>
                                                    {% endfor %}

                        </div>
                    </div>
                    <!-- Tags End -->
                </div>
{% endblock %}

templates/search_post.html
{% extends 'base.html' %}
{% block content %}
    {% if searched %}
    <h1>Searched{{ searched }}</h1>
    {% else %}
        <h1>don't fund {{ searched }}</h1>
{% endif %}
{% endblock %}

templates/single.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap_icons %}
{% load static %}
{% load embed_video_tags %}
{% block content %}
<body>

    <!-- Navbar Start -->
    </div>
    <!-- Navbar End -->


    <!-- Breadcrumb Start -->
    <div class="container-fluid">
<!--        <div class="container">-->
<!--            <nav class="breadcrumb bg-transparent m-0 p-0">-->
<!--                <a class="breadcrumb-item" href="#">Home</a>-->
<!--                <a class="breadcrumb-item" href="#">Category</a>-->

<!--                {% for category in categories %}-->
<!--                <a class="breadcrumb-item" href="{% url 'posts:category' category.pk %}">{{ category.title }}</a>-->
<!--                {% endfor %}-->
<!--            </nav>-->
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- News With Sidebar Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- News Detail Start -->
                    <div class="position-relative mb-3">
                        <div>
                                                        <h3 class="mb-3">{{ post.title }}</h3>
                        </div>
                        {% if post.image %}
                        <img class="img-fluid w-100" src="{{ post.image.url }}" style="object-fit: cover;">
                {% else %}
                          {% video post.video as my_video  %}
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="{{ my_video.url }}" allowfullscreen></iframe>
</div>


<!-- <iframe  src="{{ my_video.url  }}"></iframe>-->

  {% endvideo %}
                        {% endif %}


                        <div class="overlay position-relative bg-light">
                            <div class="mb-3">
                                <a href="">{{ post.category }}</a>
                                <span class="px-1">/</span>
                                                 <i class="text-center"><span>{% bs_icon 'clock' size='1.0em' %}{{ post.post_date }}</span></i>
                                <span>/</span>
                                                                  <i> {% bs_icon 'eye' size='1.0em' %}{{ post.views }}</i>


                            </div>
                            {% if post.audio %}
                            <audio controls  src="{{ post.audio.url }}" >{{post.audio}}</audio>
                            {% endif %}
                        <a class="h4 m-0 text-white" href=""></a>

                            <div>
                                                               <h4 class="mb-3">{{ post.text|safe }}</h4>

                                <p></p>
                            </div>
                        </div>
                    </div>
                    <p>{% translate 'Muolif' %}: {{post.owner}}</p>

                </div>

                <div class="col-lg-4 pt-3 pt-lg-0">
                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">{% translate "Follow Us" %}</h3>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="https://www.facebook.com/ismatillo.ismatov.7" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #39569E;">
                                <small class="fab fa-facebook-f mr-2"></small><small>12,345 Fans</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #52AAF4;">
                                <small class="fab fa-twitter mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #0185AE;">
                                <small class="fab fa-linkedin-in mr-2"></small><small>12,345 Connects</small>
                            </a>
                            <a href="https://www.instagram.com/ismatilloismatov/" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #C8359D;">
                                <small class="fab fa-instagram mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                        <div class="d-flex mb-3">
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none mr-2" style="background: #DC472E;">
                                <small class="fab fa-youtube mr-2"></small><small>12,345 Subscribers</small>
                            </a>
                            <a href="" class="d-block w-50 py-2 px-3 text-white text-decoration-none ml-2" style="background: #1AB7EA;">
                                <small class="fab fa-vimeo-v mr-2"></small><small>12,345 Followers</small>
                            </a>
                        </div>
                    </div>
                    <!-- Social Follow End -->



                    <!-- Ads Start -->
                    <div class="mb-3 pb-3">
                    </div>
                    <!-- Ads End -->

                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tranding</h3>
                        </div>
                                 {% for p in most_view %}

                        <div class="d-flex mb-3">
                            {% if p.image %}
                            <img src="{{ p.image.url  }}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                  <i> {% bs_icon 'eye' size='1.0em' %}{{ p.views }}</i>
                                    <span class="px-1">/</span>

                                    <i class="text-center"><span>{% bs_icon 'clock' size='1.0em' %}{{ p.post_date }}</span></i>

                                </div>
                                <a class="h6 m-0" href="{% url 'posts:post-detail' p.pk %}">{{ p.title|slice:50 }}</a>
                            </div>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        {% if post.tag %}
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tags</h3>
                        </div>
                           {% for tag in post.tag.all%}
                    <a href="{% url 'posts:tag_view' tag.id %}" class="btn btn-sm btn-outline-secondary m-1">{{ tag.title }}</a>
                {% endfor %}
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>
</body>
{% endblock %}